# Generated by Django 5.1.1 on 2024-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Выполнено'), ('IN_PROGRESS', 'В процессе'), ('NOT_COMPLETED', 'Не выполнено')], default='NOT_COMPLETED', max_length=15),
        ),
    ]
